name: Run Spring Initializr
on:
  push:
    branches:
      - main
jobs:
  generate-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
#      - name: Setup Java JDK
#        uses: actions/setup-java@v3.3.0
#        with:
#          java-version: 17
#          distribution: zulu
#          cache: maven

      - name: Install Spring CLI
        run: |
          brew tap spring-io/tap
          brew install spring-boot
      
      - name: Initialize Spring project
        run: spring init --dependencies=web
          
      - name: Unzip Spring project
        run: unzip demo.zip

#      - name: Remove initialization workflow
#        run: rm .github/workflows/init_repository.yml
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Initialize Spring project
          title: Initialize Spring project
          delete-branch: true
